[package]
name = "simple-initd"
version = "0.1.0"
edition = "2024"

[dependencies]
errno = "0.3.14"
libc = "0.2.186"
rustix = { version = "1.1.4", features = ["fs", "mount", "process", "runtime", "event", "stdio"] }

[[bin]]
name = "simple-initd"
path = "src/main.rs"

[[bin]]
name = "bad-parent"
path = "src/bin/bad_parent.rs"
